
# Service name
service: sls-ffmpeg

custom:
  # Configure these
  serverless-offline:
    port: 4000

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 300
  stage: ${file(./config.yml):stage}
  region: ${file(./config.yml):region}
  memorySize: ${file(./config.yml):memorySize}
  iamRoleStatements:
    # List buckets
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  ffmpeg:
    handler: handler.main
    events:
      - http:
          method: post
          path: /